use std::error::Error;
use gitit::start;

fn main() -> Result<(), Box<dyn Error>> {
    start()
}